config/routes.rb
RememberList::Application.routes.draw do
  resources :remembers

  get 'pages/home'
  
  match '/', :to => 'remembers#index' 

end

app/models/remember.rb
#create_table :remembers do |t|
#  t.string :name
#  t.string :tags
#  t.text :short_desc
#  t.text :full_desc
#  t.string :ref_name
#  t.boolean :active
#  t.string :ref_type
#  t.timestamps
require 'csv'
      
class Remember < ActiveRecord::Base
  
  attr_accessible :active, :full_desc, :name, :ref_name, :ref_type, :short_desc, :tags, :tag_id

  belongs_to :Tag
  
  before_save :tagscreate

  

  def tagscreate()
    short_word_length=5
    tag_numbers=5


    a=full_desc.mb_chars.downcase.to_s+" "+short_desc.mb_chars.downcase.to_s
    a=a.split(" ")
    b=WordVariation.joins(:UniqueWord).where(:variation_word =>  a,
                                             :unique_words => {:word_type => 'noun' } ).map { |h| h.unique_word.mb_chars.downcase.to_s }
    b=b.select {|v| v.split("").count >= short_word_length }
    b=b.sort_by {|i| b.count(i) }.reverse.uniq.first(tag_numbers)
    self.tags=b.join(" ").to_s 
      
  end


end

  def WordVariationToCSV()
    imax=1000
    icnt=400000
    k=10
#    f=CSV.open('app/assets/files/lingvo/ru/WordsVariations.csv', "r").each do |row|
#      unless row.nil?
#        row.drop(row.count)  
#      end  
#    end

    f=CSV.open('app/assets/files/lingvo/ru/WordsVariations.csv', "ab")
 
    WordVariation.find_each(:start => icnt*(k-1), :conditions => "id < "+(icnt*k).to_s, :batch_size => imax) do |row| 
      f << row.attributes.values.first(5)
    end
    f.close

  end

  def UniqueWordToCSV()
    imax=100000
    i=0
    f=CSV.open('app/assets/files/lingvo/ru/UniqueWords.csv', "r").each do |row|
      unless row.nil?
        row.drop(row.count)  
      end  
    end
    f=CSV.open('app/assets/files/lingvo/ru/UniqueWords.csv', "wb")
    UniqueWord.first(imax).each do |row|
      f << row.attributes.values.first(4)
      i=i+1
    end  
    f.close

    return i.to_s
  end
  

  def AddIdOfUniqueWord()
    icnt=1
    imax=1
    ii=0
    s=Array.new(imax)
    icnt.times do |k|
      a=WordVariation.where("unique_word_id isnull").first(imax)
      if a.nil?
        break
      end
      
      imax.times {|j| s[j]=a[j].unique_word.mb_chars.downcase.to_s } #.force_encoding('ASCII-8BIT')
      b=UniqueWord.all(:conditions => { :unique_word => s })
      for i in 0..imax do
        if not a[i].nil?
          unless (b.nil? or b.find { |h| h['unique_word'] == a[i].unique_word.mb_chars.downcase.to_s }.nil?)
            j=b.find { |h| h['unique_word'] == a[i].unique_word.mb_chars.downcase.to_s }['id']
          else
            j='-1'
          end
          
          if not j.nil?
            a[i].unique_word_id=j
            a[i].save
            ii=ii+1
          end
        end  
      end
    end  
    
    return ii.to_s+ "  "+j.to_s #ss#.Encoding.default_internal#b.unique_word#a.unique_word+" + "+a.id.to_s+" + "+
  end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :tag #, Remember_id
  
  belongs_to :Word_variation, :foreign_key => "word_variation"
  has_many :Remembers
  
end

app/models/unique_word.rb
#create_table :unique_words do |t|
#  t.string :unique_word
#  t.string :unique_word_desc
#  t.string :language
#  t.string :word_type

#t.index :unique_word
#t.index :language
#t.index :word_type

#  t.timestamps

class UniqueWord < ActiveRecord::Base
  attr_accessible :language, :unique_word, :unique_word_desc, :word_type, :id
  
  has_many :WordVariations

  def PopulateUniqueWord()
    temp_name=""
    temp_type=""
    i=0
    UniqueWord.delete_all
    CSV.open('app/assets/files/lingvo/ru/Word_sense_list.csv', "r").each do |row|
      if temp_name<=>row[0]
        if row[1].match("t:noun")==nil
            temp_type = ''
          else
            temp_type='noun'
        end  
        UniqueWord.create(:unique_word => row[0].last(row[0].length-2),
                          :unique_word_desc => row[1],
                          :language => "ru",
                          :word_type =>temp_type)
      end
      i =i+1
#      break if i > 10
    end    
  end
end

app/models/word_variation.rb
# encoding: utf-8
#create_table :word_variations do |t|
#      t.string :variation_word
#      t.string :unique_word
#      t.string :variation_word_desc
#      t.references :unique_word
#      
#      t.timestamps
#    end
#      
#    add_index :word_variations, :variation_word
#    add_index :word_variations, :unique_word
#    add_index :word_variations, :unique_word_id
      
class WordVariation < ActiveRecord::Base

  attr_accessible :variation_word, :variation_word_desc, :unique_word, :unique_word_id
  
  belongs_to :UniqueWord, :foreign_key => "unique_word_id"
  has_many :Tags
  
  def self.downcase()
    mb_chars.downcase.to_s
  end

end


  def PopulateVariationWord(tags)
    i=0
    imax=200000
    idmin=300784 #WordVariation.find_by_id (:first)
    idmax=tags.to_i #idmin+1001 #WordVariation.find_by_id (:last)
    
#    WordVariation.delete_all
  
    CSV.open('app/assets/files/lingvo/ru/Word_sense_variation_list.csv', "r").each do |row|
      if i>=(idmax-idmin)     
        WordVariation.create(:variation_word => row[0],
                          :unique_word => row[1],
                          :variation_word_desc => row[2])
      end
      i =i+1
      break if (i >= (imax+idmax-idmin))
    end
    return (idmax+imax).to_s
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title='Home'
  end
end

app/controllers/remembers_controller.rb
class RemembersController < ApplicationController
  def index
    @remembers = Remember.paginate(:page => params[:page], :per_page => 10)
  end

  def show
    @remember = Remember.find(params[:id])
  end

  def new
    @remember = Remember.new
  end

  def edit
    @remember = Remember.find(params[:id])
  end

  def create
    @remember = Remember.new(params[:remember])

    if @remember.save
      redirect_to @remember, notice: 'Remember was successfully created.'
    else
      render action: "new" 
    end
  end

  def update
    @remember = Remember.find(params[:id])

    if @remember.update_attributes(params[:remember])
      redirect_to @remember, notice: 'Remember was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    @remember = Remember.find(params[:id])
    @remember.destroy
    redirect_to remembers_url 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    base_title = "TITLE"
    if @title.nil?
      base_title
    else
#      "#{base_title} | #{@title}"
      "#{@title}"
    end    
  end

  def logo
    image_tag("imgLogo.jpg", :alt => "Remember me", :class => "imgLogo")
  end
  

  
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/remembers_helper.rb
module RemembersHelper


end

app/views/layouts/_footer.html.erb
<footer>
  <nav class="round">
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
  <%= link_to logo, remembers_path %>
  <div class="title"><h1>You are here to store information</h1></div>
  <nav id="topRightMenu" class="horisontalMenu">
    <a class="hirosontalMenuItem"><%= link_to "Home", remembers_path %></a> | 
    <a class="hirosontalMenuItem"><%= link_to "Search", '#' %></a> | 
    <a class="hirosontalMenuItem"><%= link_to "Settings", '#' %></a> | 
  </nav>
  <div class="clear"></div>  
</header>

app/views/layouts/_preview.html.erb
<% unless @remember.nil? %>

<% end %>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag "application", :media => "screen" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tag %>
    <%= stylesheet_link_tag "application" %>
    <%= render "layouts/stylesheets" %>  </head>
    <%= javascript_include_tag "application" %>
  </head>
  <body>
    <div id="bodyContainer" class="bodyContainer">
      <aside><%= render "layouts/header" %></aside>
      
      <div id="contentContainer" class="contentContainer">
        <aside><%= render "layouts/filter" %></aside>
        
        <section>
          <%= yield %>    
        </section>
        
        <%= render :partial => "layouts/preview", :object => @remember %>      
      </div>
      
      <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/remembers/_form.html.erb
<%= form_for(@remember) do |f| %>
  <% if @remember.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@remember.errors.count, "error") %> prohibited this remember from being saved:</h2>

      <ul>
      <% @remember.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="rememberEditItem">
    <div>
      <div class="rememberEditItemLabel"><%= f.label :name %>: </div>
      <div class="rememberEditItemField"><%= f.text_field :name %></div><div class="clear"></div>
    </div>
    <div>
      <div class="rememberEditItemLabel"><%= f.label :tags %></div>
      <div class="rememberEditItemField"><%= f.text_field :tags %></div>
      <div class="clear"></div>
    </div>
    <div>
      <div class="rememberEditItemLabel"><%= f.label :short_desc %></div>
      <div class="rememberEditItemField"><%= f.text_area :short_desc, :size => "10x5" %></div>
      <div class="clear"></div>
    </div>
    <div>
      <div class="rememberEditItemLabel"><%= f.label :full_desc %></div>
      <div class="rememberEditItemField"><%= f.text_area :full_desc, :size => "60x12" %></div>
      <div class="clear"></div>
    </div>
    <div>
      <div class="rememberEditItemLabel"><%= f.label :ref_type %></div>
      <div class="rememberEditItemField"><%= f.select :ref_type, ["Internet", "File"] %></div>
      <div class="clear"></div>
    </div>
    <div>
      <div class="rememberEditItemLabel"><%= f.label :ref_name %></div>
      <div class="rememberEditItemField"><%= f.text_field :ref_name %></div>
      <div class="clear"></div>
    </div>
    <div>
      <div class="rememberEditItemLabel"><%= f.label :active %></div>
      <div class="rememberEditItemField"><%= f.check_box :active %></div>
      <div class="clear"></div>
    </div>

    <div class="actions">
      <%= f.submit %><br>
    </div>
    <div class="clear"></div>
  </div>
<% end %>

app/views/remembers/edit.html.erb
<div class="rememberEditItem">
  <div class="RememberEditMenu">
    <a><%= link_to "Show", @remember %></a>
    <a><%= link_to "Back", remembers_path %></a>
  </div>
  
  <%= render "form" %>
  
  <div class="RememberEditMenu">
    <a><%= link_to "Show", @remember %></a>
    <a><%= link_to "Back", remembers_path %></a>
  </div>
  
</div>

app/views/remembers/index.html.erb
<div class=rememberList>
    <div id="notice"><%= notice %></div>
  <div class=rememberListPaginate><%= will_paginate %></div>
  <div class=remembersCaption><a> </a></div>
  <% @remembers.each do |remember| %>

  <div class=rememberListItem>
    <div class= rememberListItemName>Name: <a href=<%= remember.ref_name%> ><%= remember.name %></a></div>
    <div class=rememberListItemMain>
      <a>Tags: <%= remember.tags %><a/>
    </div>
    <div class=rememberListMenu>
        <a><%= link_to "New", new_remember_path %></a>
        <a><%= link_to "Show", remember %></a>
        <a><%= link_to "Edit", edit_remember_path(remember) %></a>
        <a><%= link_to "Destroy", remember, method: :delete, data: { confirm: "Are you sure?" } %></a>
    </div>
    <div class="clear"></div>  
    <div class=rememberListItemDesc><%= remember.short_desc %></div>
  </div>
  <div class=rememberListItemBreak></div>

  <% end %>
  <div class=rememberListPaginate><%= will_paginate %></div>
</div>

app/views/remembers/new.html.erb
<div class="rememberEditItem">
  <div class="RememberEditMenu">
    <a><%= link_to "Back", remembers_path %></a>
  </div>
  
  <%= render "form" %>
  
  <div class="RememberEditMenu">
    <a><%= link_to "Back", remembers_path %></a>
  </div>
  
</div>

app/views/remembers/show.html.erb
<div class=rememberShowItem>
  <div id="notice"><%= notice %></div>
  <div class=RememberShowMenu>
    <a><%= link_to "Edit", edit_remember_path(@remember) %></a>
    <a><%= link_to "Back", remembers_path %></a>
  </div>
  
  <div><b>Name: </b><a href=<%= @remember.ref_name%> ><%= @remember.name %></a></div>
  <div><a><b>Tags: </b><%= @remember.tags %><a/></div>    
  <div class=rememberShowItemShortDesc><b>Short Description: </b><%= @remember.short_desc %></div>
  <div class=rememberShowItemFullDesc><b>Full Description: </b><%= @remember.full_desc %></div>
  <div><b>Ref name: </b><a href=<%= @remember.ref_name %> ><%= @remember.ref_name %></a></div>
  <div><b>Active: </b><%= @remember.active %></div>
  <div><b>Ref type: </b><%= @remember.ref_type %></div>
  
  <div class=RememberShowMenu>
    <a><%= link_to "Edit", edit_remember_path(@remember) %></a> |
    <a><%= link_to "Back", remembers_path %></a>
  </div>
  
</div>